### ISSUE TITLE
feat: create a argsh cli (EYODF)

### ISSUE THREAD

**Issue by divramod** [fentas/argsh#2]
As a developer i regularly create new scripts. So it would be nice to have a argsh cli tool which helps me with the repeating tasks i have to do while using argsh. As argsh is a cli tool creation helper it could "eat its own dog food".

# ToDo
* [ ] create the cli tool (use argsh)
* [ ] feat: create argsh script ```argsh -I | --init```
* [ ] feat: run tests #3 ```argsh -T --path /path/to/your/tests```
* [ ] feat: code coverage #4 ```argsh -C --path /path/to/your/tests```

**Comment by fentas** [comment]
I don't know if this is overkill? Maybe more documentation and creation of snippets?

**Comment by divramod** [comment]
it could be done with snippets too. in fact, that's how i do it currently.
i think its more a question of convenience.
```argsh -I``` would be much easier and faster for new users of the tool than creating code snippets.
Also the point of eating your own dog food is nice as another example for args.sh usage.
