### ISSUE TITLE
feat: debug options

### ISSUE THREAD

**Issue by divramod** [fentas/argsh#5]
As a developer, it sometimes happens that i need to see which values the options i passed to script have. For being able to see that effortlessly, it would be nice to have a functions which prints out this information using a readable format.

## ToDo
* [ ] create the function
* [ ] add a debug-options flag for one option
* [ ] add a debug-options flag for all options
```
# example 1: print one option
hetzner --debug-options SERVER_TYPE
SERVER_TYPE: environment: <empty>; default: 'cx11'; passed: 'cx21'; current: 'cx31'

# example 2: print all options
hetzner --debug-options
```
